# Generated by Django 4.2.7 on 2023-12-20 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import testapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Info',
            fields=[
                ('test_id', models.TextField(primary_key=True, serialize=False)),
                ('test_title', models.TextField()),
                ('test_desc', models.TextField()),
                ('test_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=testapp.models.user_directory_path)),
                ('type', models.TextField()),
                ('encoding', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Questions',
            fields=[
                ('section_id', models.TextField(primary_key=True, serialize=False)),
                ('section_name', models.TextField()),
                ('section_desc', models.TextField()),
                ('test_questions', models.JSONField()),
                ('test_answers', models.JSONField()),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.test_info')),
            ],
        ),
        migrations.CreateModel(
            name='Test_Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField()),
                ('proctoring_score', models.IntegerField()),
                ('test_score', models.IntegerField()),
                ('section_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.test_questions')),
                ('test_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.test_info')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
